# Use this compose file to spin up services to support your local development of Nesis
# docker-compose -f compose-dev.yml up

version: '3'

networks:
  nesis:
    driver: overlay
    attachable: true

services:
  memcached:
    image: bitnami/memcached:1.6.19
    ports:
      - "11211:11211"
    networks:
      - nesis
  samba:
    image: andyzhangx/samba:win-fix
    command: ["-u", "username;password", "-s", "share;/smbshare/;yes;no;no;all;none", "-p"]
    ports:
      - '2445:445'
    networks:
      - nesis
    volumes:
      - 'samba_data2:/smbshare'
    environment:
      - USERNAME=username
      - PASSWORD=password
  minio:
      image: docker.io/bitnami/minio:2022
      ports:
        - '59000:9000'
        - '59001:9001'
      networks:
        - nesis
      volumes:
        - 'minio_data:/data'
      environment:
        - MINIO_ROOT_USER=your_username
        - MINIO_ROOT_PASSWORD=your_password
        - MINIO_DEFAULT_BUCKETS=documents
  postgres16:
    image: "ametnes/postgresql:16-debian-12"
    ports:
      - "65432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nesis
    volumes:
      - postgres16_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - nesis
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 16333:6333
      - 16334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant_data
    networks:
      - nesis
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      # Default configuration for persist_directory in chromadb/config.py
      # Currently it's located in "/chroma/chroma/"
      - chroma-data:/chroma/chroma/
    ports:
      - 18000:8000
    networks:
      - nesis

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - START_WEB=0
      - LAMBDA_REMOTE_DOCKER=0
      - DATA_DIR=/localstack/data
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - local_stack:/localstack/data
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa55woR.d12345"
    ports:
      - "11433:1433"
#    volumes:
#      - mssql_data:/var/opt/mssql
    networks:
      - nesis
volumes:
  minio_data:
  samba_data2:
  postgres16_data:
  qdrant_data:
  chroma-data:
  local_stack:
  mssql_data:
