"""migrations-0.0.2

Revision ID: 953b4d309aaa
Revises: 79ec864b571e
Create Date: 2024-04-09 19:11:08.664346

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "953b4d309aaa"
down_revision: Union[str, None] = "79ec864b571e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("datasource_name_key", "datasource", type_="unique")
    op.create_unique_constraint("uq_datasource_name", "datasource", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_datasource_name", "datasource", type_="unique")
    op.create_unique_constraint("datasource_name_key", "datasource", ["name"])
    # ### end Alembic commands ###
