database:
    url: postgresql://postgres:password@localhost:65432/nesis
    debug: false

rag:
    endpoint: "http://localhost:8080"
    mode: "ingest"
    extractions:
        store:
            url: postgresql://postgres:password@localhost:65432/nesis

service:
    port: 6000
    host: "0.0.0.0"


tasks:
    job:
        stores:
            url:  postgresql://postgres:password@localhost:65432/nesis

