database:
    url: postgresql://postgres:password@localhost:65432/nesis
    debug: false

rag:
    endpoint: "http://localhost:8080"

service:
    port: 6000
    host: "0.0.0.0"
    mlengine: {"exclude_datasources": ["web", "mindsdb"]}


tasks:
    job:
        stores:
            url:  postgresql://postgres:password@localhost:65432/nesis

