database:
    url: postgresql://postgres:password@localhost:65432/nesis
    debug: false

llm:
    endpoint: "http://localhost:9080"

service:
    port: 6000
    host: "0.0.0.0"
    mlengine: {"exclude_datasources": ["web", "mindsdb"]}


tasks:
    fetch_documents:
        enabled: true
#      schedule: 2
    generate_data_documents:
        enabled: false
