api:
  env:
    # - name: LOG_LEVEL
    #   value: DEBUG
    - name: NESIS_ADMIN_EMAIL
      value: test@domain.com
    - name: NESIS_ADMIN_PASSWORD
      value: password

rag:
  enabled: true
  podSecurityContext:
    fsGroup: 400
  securityContext:
    runAsUser: 500
    runAsGroup: 400

  persistence:
    enabled: true
    size: 10Gi
  
  extraEnv:
    - name: OPENAI_API_KEY
      value: sk-
    # - name: OPENAI_API_BASE
    #   value: http://
  config: null
