name: Test Helm Chart

on:
  push:
    paths:
      - "helm/templates/**"
  pull_request:
    paths:
      - "helm/templates/**"

env:
  HELM_VERSION: 3.6.3

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Helm Charts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: "${{ env.HELM_VERSION }}"

      - name: Install unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run unit tests
        run: helm unittest ./helm
